CREATE TABLE "member" (
    "member_id"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nickname"      VARCHAR(50) NOT NULL,
    "status"        VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    "manner_temp"   SMALLINT NOT NULL DEFAULT 365,
    "phone_number"  VARCHAR(20) UNIQUE NOT NULL,
    "profile_image" VARCHAR(500),
    "created_at"    TIMESTAMP NOT NULL,
    "updated_at"    TIMESTAMP NOT NULL,
    "withdrawn_at"  TIMESTAMP
);

CREATE TABLE "region" (
    "id"      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "adm_nm"  VARCHAR(50) NOT NULL,
    "adm_cd"  VARCHAR(8) NOT NULL,
    "adm_cd2" VARCHAR(10) NOT NULL,
    "sgg"     VARCHAR(5) NOT NULL,
    "sido"    VARCHAR(2) NOT NULL,
    "sidonm"  VARCHAR(20) NOT NULL,
    "sggnm"   VARCHAR(20) NOT NULL,
    "dongnm"  VARCHAR(20) NOT NULL,
    "geom"    geometry(MultiPolygon, 4326) NOT NULL
);

CREATE TABLE "member_region" (
    "member_id"   BIGINT NOT NULL,
    "region_id"   INT NOT NULL,
    "is_primary"  BOOLEAN NOT NULL DEFAULT FALSE,
    "verified_at" TIMESTAMP,
    "created_at"  TIMESTAMP NOT NULL
);

CREATE TABLE "listing" (
    "listing_id"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "seller_id"      BIGINT NOT NULL,
    "buyer_id"       BIGINT,
    "title"          VARCHAR(200) NOT NULL,
    "description"    TEXT,
    "category_id"    BIGINT,
    "price"          BIGINT NOT NULL DEFAULT 0,
    "is_free"        BOOLEAN,
    "is_hidden"      BOOLEAN,
    "status"         VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    "hope_region_id" INT,
    "hope_lat"       DECIMAL(10, 7),
    "hope_lng"       DECIMAL(10, 7),
    "view_count"     BIGINT NOT NULL DEFAULT 0,
    "created_at"     TIMESTAMP NOT NULL,
    "updated_at"     TIMESTAMP NOT NULL,
    "deleted_at"     TIMESTAMP
);

CREATE TABLE "listing_image" (
    "image_id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "listing_id" BIGINT NOT NULL,
    "image_url"  VARCHAR(500) NOT NULL,
    "sort_order" INT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL
);

CREATE TABLE "listing_waiter" (
    "listing_id" BIGINT NOT NULL,
    "member_id"  BIGINT NOT NULL
);

CREATE TABLE "member_interest" (
    "interest_id" BIGINT PRIMARY KEY,
    "member_id"   BIGINT NOT NULL,
    "listing_id"  BIGINT NOT NULL
);

CREATE TABLE "appointment" (
    "appointment_id"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "listing_id"        BIGINT NOT NULL,
    "seller_id"         BIGINT NOT NULL,
    "buyer_id"          BIGINT NOT NULL,
    "status"            VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    "notification_time" TIMESTAMP,
    "meet_at"           TIMESTAMP NOT NULL,
    "meet_place_text"   VARCHAR(200),
    "meet_lat"          DECIMAL(10, 7),
    "meet_lng"          DECIMAL(10, 7),
    "created_at"        TIMESTAMP NOT NULL,
    "updated_at"        TIMESTAMP NOT NULL
);

CREATE TABLE "chat_room" (
    "chat_room_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "listing_id"   BIGINT NOT NULL,
    "seller_id"    BIGINT NOT NULL,
    "buyer_id"     BIGINT NOT NULL,
    "status"       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    "created_at"   TIMESTAMP NOT NULL,
    "updated_at"   TIMESTAMP NOT NULL
);

CREATE TABLE "chat_message" (
    "message_id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "chat_room_id" BIGINT NOT NULL,
    "sender_id"    BIGINT NOT NULL,
    "type"         VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    "content"      TEXT NOT NULL,
    "created_at"   TIMESTAMP NOT NULL
);

CREATE TABLE "chat_read" (
    "chat_room_id"         BIGINT NOT NULL,
    "member_id"            BIGINT NOT NULL,
    "last_read_message_id" BIGINT,
    "updated_at"           TIMESTAMP NOT NULL
);

CREATE TABLE "trade" (
    "trade_id"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "listing_id"   BIGINT NOT NULL,
    "seller_id"    BIGINT NOT NULL,
    "buyer_id"     BIGINT NOT NULL,
    "price"        BIGINT NOT NULL,
    "status"       VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    "completed_at" TIMESTAMP,
    "created_at"   TIMESTAMP NOT NULL,
    "updated_at"   TIMESTAMP NOT NULL
);

CREATE TABLE "review" (
    "review_id"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "trade_id"   BIGINT NOT NULL,
    "listing_id" BIGINT NOT NULL,
    "writer_id"  BIGINT NOT NULL,
    "target_id"  BIGINT NOT NULL,
    "is_seller"  BOOLEAN NOT NULL DEFAULT FALSE,
    "rating"     INT NOT NULL,
    "comment"    TEXT,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "notification" (
    "notification_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "member_id"       BIGINT NOT NULL,
    "type"            VARCHAR(30) NOT NULL,
    "is_read"         BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at"      TIMESTAMP NOT NULL,
    "read_at"         TIMESTAMP
);

CREATE TABLE "keyword_subscription" (
    "subscription_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "member_id"       BIGINT NOT NULL,
    "keyword"         VARCHAR(100) NOT NULL,
    "region_id"       INT,
    "created_at"      TIMESTAMP NOT NULL
);

CREATE TABLE "outbox_event" (
    "event_id"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "aggregate_type" VARCHAR(50) NOT NULL,
    "aggregate_id"   BIGINT NOT NULL,
    "event_type"     VARCHAR(50) NOT NULL,
    "payload_json"   JSON NOT NULL,
    "status"         VARCHAR(20) NOT NULL DEFAULT 'NEW',
    "occurred_at"    TIMESTAMP NOT NULL,
    "published_at"   TIMESTAMP
);

CREATE TABLE "inbox_event" (
    "event_id"     BIGINT NOT NULL,
    "consumer"     VARCHAR(50) NOT NULL,
    "processed_at" TIMESTAMP NOT NULL
);